apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: chatbot-h1742385572372
  janus-idp.io/tekton: chatbot-h1742385572372
  backstage.io/kubernetes-id: chatbot-h1742385572372
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: chatbot-h1742385572372
resources:
  - application-dev.yaml
