apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: chatbot-h1742385572372
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-h1742385572372
  name: chatbot-h1742385572372
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
