apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: chatbot-h1742385572372
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-h1742385572372
  name: chatbot-h1742385572372
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: chatbot-h1742385572372
